# INTERACTIVE_MODELS_PATH: "./weights"
# INTERACTIVE_MODELS_PATH: "/playpen-raid/qinliu/models/model_1012_2021/iter_mask/pascal_hrnet18/001/checkpoints"
# INTERACTIVE_MODELS_PATH: "/playpen-raid/qinliu/models/model_1015_2021/iter_mask/pascal_segformerb5/005_pretrain_b2/checkpoints"
INTERACTIVE_MODELS_PATH: "/playpen-raid/qinliu/models/model_1016_2021/iter_mask/cocolvis_segformerb2/000_cocolvis/checkpoints"
EXPS_PATH: "/playpen-raid/qinliu/models/model_1113_2021"

# Evaluation datasets
GRABCUT_PATH: "/playpen-raid/qinliu/data/GrabCut"
BERKELEY_PATH: "/playpen-raid/qinliu/data/Berkeley"
DAVIS_PATH: "/playpen-raid/qinliu/data/DAVIS"
COCO_MVAL_PATH: "/playpen-raid/qinliu/data/COCO_MVal"

# Train datasets
SBD_PATH: "/playpen-raid/qinliu/data/SBD/dataset"
COCO_PATH: "/playpen-raid/qinliu/data/COCO_2017"
LVIS_v1_PATH: "/playpen-raid/qinliu/data/COCO_2017"
OPENIMAGES_PATH: "./datasets/OpenImages"
PASCALVOC_PATH: "/playpen-raid/qinliu/data/PascalVOC"
ADE20K_PATH: "./datasets/ADE20K"
BraTS_PATH: "/playpen-raid/qinliu/data/BraTS20"
ssTEM_PATH: "/playpen-raid/qinliu/data/ssTEM"

# You can download the weights for HRNet from the repository:
# https://github.com/HRNet/HRNet-Image-Classification
IMAGENET_PRETRAINED_MODELS:
  HRNETV2_W18: "./weights/pretrained/hrnetv2_w18_imagenet_pretrained.pth"
  HRNETV2_W32: "./weights/pretrained/hrnetv2_w32_imagenet_pretrained.pth"
  HRNETV2_W32_SOTA: "./weights/coco_lvis_h32_itermask.pth"
  HRNETV2_W40: "./weights/pretrained/hrnetv2_w40_imagenet_pretrained.pth"
  HRNETV2_W48: "./weights/pretrained/hrnetv2_w48_imagenet_pretrained.pth"
  HRNETV2_W64: "./weights/pretrained/hrnetv2_w64_imagenet_pretrained.pth"
  MIT_B5: "./weights/pretrained/mit_b5_converted.pth"
  MIT_B4: "./weights/pretrained/mit_b4_converted.pth"
  MIT_B3: "./weights/pretrained/mit_b3_converted.pth"
  MIT_B2: "./weights/pretrained/mit_b2_converted.pth"
  MIT_B1: "./weights/pretrained/mit_b1_converted.pth"
  MIT_B0: "./weights/pretrained/mit_b0_converted.pth"
  HRF_BASE: "./weights/pretrained/hrt_base.pth"
